name: Build Docker image

on: push

env:
  AWS_REGION: eu-central-1
  FUNCTION_NAME_UNK: funaunk
  FUNCTION_NAME_STAGING_FOO: funastfoo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push Container
        run: |
          docker build -t app:${{ github.sha }} .

      - run: echo hello ${{ vars.RETICULATE_NAME }} $RETICULATE_NAME

  deploy_production_foo:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to production_foo
    environment: production_foo
    if: github.ref == 'refs/heads/production_foo'
  
    steps:
      - run: echo hello ${{ vars.RETICULATE_NAME }} $RETICULATE_NAME

  deploy_staging_foo:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to staging_foo
    environment: staging_foo
    if: github.ref == 'refs/heads/main'
    
    env:
      FUNCTION_NAME_D: $FUNCTION_NAME_STAGING_FOO
      FUNCTION_NAME_VARS: ${{ vars.FUNCTION_NAME_STAGING_FOO }}
      # FUNCTION_NAME_ENV: ${{ env.FUNCTION_NAME_STAGING_FOO }}
  
    steps:
      - run: echo hello ${{ vars.RETICULATE_NAME }} $RETICULATE_NAME
      - run: export | grep FUN
      - run: echo env.FUNCTION_NAME_STAGING_FOO ${{ env.FUNCTION_NAME_STAGING_FOO }}
      - run: echo env.FUNCTION_NAME_VARS ${{ env.FUNCTION_NAME_VARS }}

  deploy_staging_bar:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to staging_bar
    environment: staging_bar
    if: github.ref == 'refs/heads/staging_bar'
  
    steps:
      - run: echo hello ${{ vars.RETICULATE_NAME }} $RETICULATE_NAME

  deploy_unknown:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to unknown
    environment: unknown # spusti se tohle, i kdyz tento environment neni v settings repozitare?
    #if: github.ref == 'refs/heads/main'
  
    steps:
      - run: echo hello ${{ vars.RETICULATE_NAME }} $RETICULATE_NAME 
        # tady snad zadne RETICULATE_NAME neni, kdyz je definovane jen v tech ostatnich environments
