name: Build Docker image

on: push

env:
  AWS_REGION: eu-central-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Push Container
        run: |
          docker build -t app:${{ github.sha }} .
